name: animalcargo
description: Animal Cargo

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  shared_preferences: ^0.5.6+1
  google_sign_in: ^4.1.1
  path_provider: ^1.6.0
  hive: ^1.3.0
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  firebase_core: ^0.4.2+1
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.12.0+1
  flutter_modular: ^1.1.1
  flutter:
    sdk: flutter


dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs